package vista;
public class frmPrincipal extends javax.swing.JFrame {

    /** Creates new form MDIPadre */
    public frmPrincipal() {
        initComponents(); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        __CONSULTAS = new javax.swing.JButton();
        __VER_PRODUCTOS = new javax.swing.JButton();
        __VER_NUEVA_VENTA = new javax.swing.JButton();
        __VER_NUEVA_COMPRA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sist. Inventa");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Inventario");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new java.awt.GridBagConstraints());

        __CONSULTAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/recursos/consultas.jpg"))); // NOI18N
        __CONSULTAS.setText("Consultas");
        __CONSULTAS.setPreferredSize(new java.awt.Dimension(160, 44));

        __VER_PRODUCTOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/recursos/catalogo.jpg"))); // NOI18N
        __VER_PRODUCTOS.setText("Catálogo de productos");
        __VER_PRODUCTOS.setPreferredSize(new java.awt.Dimension(160, 44));

        __VER_NUEVA_VENTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/recursos/registrar1.jpg"))); // NOI18N
        __VER_NUEVA_VENTA.setText("Registrar venta");
        __VER_NUEVA_VENTA.setPreferredSize(new java.awt.Dimension(160, 44));

        __VER_NUEVA_COMPRA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/recursos/proveedores.png"))); // NOI18N
        __VER_NUEVA_COMPRA.setText("Compra proveedores");
        __VER_NUEVA_COMPRA.setPreferredSize(new java.awt.Dimension(160, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(__VER_NUEVA_VENTA, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(__CONSULTAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(__VER_NUEVA_COMPRA, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__VER_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__VER_NUEVA_VENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__VER_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__CONSULTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__VER_NUEVA_COMPRA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton __CONSULTAS;
    public javax.swing.JButton __VER_NUEVA_COMPRA;
    public javax.swing.JButton __VER_NUEVA_VENTA;
    public javax.swing.JButton __VER_PRODUCTOS;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
